version: 2.1
orbs:
  cypress: cypress-io/cypress@1.10.0
workflows:
  build:
    jobs:
      - cypress/run:
          # run all tests
          command: npm test
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          post-steps:
            # store the created coverage report folder
            # you can click on it in the CircleCI UI
            # to see live static HTML site
            - store_artifacts:
                path: coverage
            # print code coverage summary to the terminal
            - run: npx nyc report

